# -*- coding: utf-8 -*-
"""HW1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xTNVhV0IonMdcjEEA34qfR69JXmCiOer
"""

A = [0,1,2,3,4,5]
l = len(A)/2
B = A[:int(l)]
C = A[int(l):]

print(B)
print(C)

m=int(0)
n=int(input('please enter one digit number: '))
even_in_range=[i for i in range(m,n+1) if i%2==0 ]
if n <=9 :
  print(even_in_range)
else:
  print("I SAID ONE DIGIT!!!")